### ISSUE TITLE
'Not found' page when clicking on the header (see figures in description)

### ISSUE THREAD

**Issue by eloparco** [enricol96/Electronic-Student-Record-Management-System#97]
![teacher_link.png](https://images.zenhubusercontent.com/5d9c828aecdcce00019797ca/2a92df4c-9251-4edb-b80f-a467f9497992)![not_found.png](https://images.zenhubusercontent.com/5d9c828aecdcce00019797ca/27f2be93-d0e2-47d5-95f4-a3551536e693)

**Comment by giovannic96** [comment]
Effective time: 0.25h
